# If true we read character and event
# from the config.yaml file. Else,
# display a form to the user to fill out
hardcode_character_and_event: false

app_is_offline: true

openai:
  model: "gpt-3.5-turbo"
  temperature_min: 0.8
  temperature_max: 0.9
  max_tokens_min: 5
  max_tokens_max: 15
  top_p: 1
  max_attempts: 2

autocomplete:
  # The deboucne time (ms) is the spacing between calls (d=700)
  debounce_time: 800

  # How many sentences (d=2) to require the user to write before we start auto-complete
  # It has to be more than 1 because we need to know the context of the sentence
  min_sentences: 1

  # What proportion (d=0.7) of auto-completes should be relevant to the event. Lower than 1 to keep
  # not so heavy haanded
  event_relevant: 0.8


characters:
  p1:
    name: "eliana"
    age: 23
    gender: "Female"
    occupation: "College Student"
    location: "Vermont"
    hobbies: ["Watching baseball", "listening to maccabeats", "eating nutella"]
    personality: "introverted, particular, quirky"

  p2:
    name: "karen"
    age: 60
    gender: "Female"
    occupation: "Social Work professor"
    location: "Oradell, NJ"
    hobbies: ["meditation", "yoga", "museums", "walking"]
    personality: "intense and ambitious and also passionate"

  p3:
    name: "Matt"
    age: 32
    gender: "Male"
    occupation: "Unemployed since got chronic illness"
    location: "Princeton, New Jersey"
    hobbies: ["computer programming", "tech and business", "travel", "fashion", "meditation"]
    personality: "friendly, care-free, non-judgemental, open-minded, and adventurous"

event:
  name: "Unchecked climate change. Specifically, two degrees of warming."
  effects:
  effects_generator_model: "gpt-3.5-turbo" # The model used to generate the effects