hardcode_character_and_event: true

openai:
  model: "gpt-3.5-turbo"
  temperature_min: 0.8
  temperature_max: 0.9
  max_tokens_min: 5
  max_tokens_max: 15
  top_p: 1
  max_attempts: 2

characters:
  eliana:
    name: "eliana"
    age: 23
    gender: "Female"
    occupation: "College Student"
    location: "Vermont"
    hobbies: ["Watching baseball", "listening to maccabeats", "eating nutella"]
    personality: "introverted, particular, quirky"

  karen:
    name: "karen"
    age: 60
    gender: "Female"
    occupation: "Social Work professor"
    location: "Oradell, NJ"
    hobbies: ["meditation", "yoga", "museums", "walking"]
    personality: "intense and ambitious and also passionate"

  alan:
    name: "jay"
    age: 32
    gender: "Male"
    occupation: "Unemployed"
    location: "Princeton, New Jersey"
    hobbies: ["computer programming", "tech and business", "travel", "fashion", "meditation"]
    personality: "friendly, care-free, non-judgemental, open-minded, and adventurous"

event:
  name: "Unchecked climate change. Specifically, two degrees of warming."
  effects: